### ISSUE TITLE
I actually feel jQuery is very good.

### ISSUE THREAD

**Issue by reason211** [oneuijs/You-Dont-Need-jQuery#128]
When I finished reading this article, I actually felt jQuery was really good. 😂

It's still simplifying a lot of things.

**Comment by tracker1** [comment]
I don't think that anyone wants to discount what jQuery has done... that said, there is a lot to it, so much so that most projects are only using less than half of it.    You have the selection engine from sizzle, in addition to event handling abstractions.  A lot of that is easy enough and consistent enough in the browsers now.  You have the promises abstractions, which is now done slightly differently in the browser, mostly native now.  You have the request models, which is now supplanted with the fetch API.  In the end, a lot of what jQuery has in the toolbox beyond DOM query, events and manipulation is better served with other tools, or native to JS and/or the browser.

I will still reach for jQuery in a lot of cases, especially if it's already in a project.  However, I'm hesitant to add it into a new project.

**Comment by webstermobile** [comment]
i think some support ie9/8.
and i also think jquery is cool

**Comment by pbuzdin** [comment]
No
вт, 24 янв. 2017 г. в 11:59, webster <notifications@github.com>:
