### ISSUE TITLE
Best way for $("#foo .bar")

### ISSUE THREAD

**Issue by adrianoresende** [oneuijs/You-Dont-Need-jQuery#141]
> document.querySelector and document.querySelectorAll are quite SLOW,

What is better way if use `$("#foo .bar")` ?

1 - `document.getElementById('foo').getElementsByClassName('bar')` ?

or 

2 - `document.querySelector('#id .bar')` ?

**Comment by kaidez** [comment]
I would say #2 is better since `getElementsByClassName` is buggy. But I would also suggest that you avoid selecting things with descendant selectors as it's an anti pattern since it's under-performant.

e.g try and do `document.querySelector('#id')` or something similar instead of `document.querySelector('#id .bar')`.
